name: Head test

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - smoke
          - acceptance

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Up site
        run: |
          git clone https://github.com/manikosto/qa-automation-sandbox
          cd qa-automation-sandbox
          docker compose up -d --build
          sleep 10   # даём время контейнерам подняться
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest ./tests -v